pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        java -version
      }
    }
    stage('Test') {
      steps {
        echo 'Testing..'
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying....'
      }
    }
  }
}